10gosu1/FE12_Team5_epigram

src/app/epigrams/[id]/page.tsx, src/app/epigrams/feed/page.tsx, src/app/page.tsx
- close #8 
랜딩페이지 반응형 디자인 추가 작업했습니다.
이전에 한솔님이 작업한대로 애니메이션도 추가했습니다!
- framer motion 적용 (스크롤 시 나타나기, 버튼 호버)
build시 오류가 나던 부분 해결 완
https://github.com/user-attachments/assets/9abd1af3-f45d-4ce8-ad40-d1a4fcdedc99
=> Feat(#8): 랜딩페이지 section1 반응형 작업

package-lock.json, package.json, src/lib/validation/auth.ts
- close #28 
- auth 로그인, 회원가입 스키마 작업
- zod를 사용하면 자동 타입 추론이 되어 활용할 수 있답니다:)
=> Feat(#28): auth 로그인, 회원가입 스키마 작업

src/lib/validation/auth.ts
- close #31 
- confirmPassword -> passwordConfirmation로 변경
=> Feat(#31): 스키마 명칭 수정

src/types/Comment.ts, src/types/Emotionlog.ts, src/types/Epigram.ts, src/types/Image.ts, src/types/Oauth.ts, src/types/User.ts
- close #24
- 백엔드 API Responses 타입 정의 작업
=> Feat(#24): 백엔드 API 타입정의 작업

src/app/auth/signup/page.tsx, src/lib/validation/auth.ts
- close #53 
기존에 만들어 뒀던 회원가입 폼과 zod 스키마를 연결만 해줬습니다!
작동은 잘 되는 것 같습니다.
=> Feat(#53): 회원가입 폼과 스키마 연결

src/app/main/_conponents/LatestEpigrams.tsx, src/app/main/page.tsx, src/hooks/useFetchEpigrams.ts
- close #67 
- 메인 : 최신 에피그램 UI
- 에피그램 데이터 조회 hook : useFetchEpigrams.ts
- 에피그램 더보기 버튼은 기능 구현이 완료되면 추가 작업하겠습니다.
=> Feat: 메인 - 최신 에피그램 구현

package-lock.json, package.json, src/app/sample/_components/Jin.tsx, src/components/UK/InfiniteList.tsx, src/lib/Epigram.ts
- close #74
InfiniteList.tsx any 타입 명시화해서 build오류 수정
=> fix: 빌드 오류 수정

src/app/feed/page.tsx, src/app/mypage/_components/MyEpigrams.tsx, src/app/mypage/_components/MyTabMenu.tsx, src/app/mypage/page.tsx, src/components/TabMenu.tsx, src/hooks/useFetchEpigrams.ts, src/lib/Epigram.ts
- close #75 
- 마이페이지 레이아웃 UI 작업 : /mypage/page.tsx
- (공용) 탭메뉴 기능 구현 : /component/TabMenu.tsx
- 마이페이지 탭메뉴 세팅 : /mypage/_components/MyTabMenu.tsx
- 마이페이지 내 에피그램 구현 : /mypage/_components/MyEpigrams.tsx
https://github.com/user-attachments/assets/5f686586-6547-434d-bee1-253a374515b5
- 더보기 기능은 추후 작업 예정입니다.
=> feat(#75): 마이페이지 레이아웃 / 탭 메뉴 기능 / 내 에피그램 구현

src/app/feed/page.tsx, src/app/main/page.tsx, src/components/TodayEmotion.tsx, src/hooks/useFetchEpigrams.ts, src/lib/Emotionlog.ts, src/lib/Epigram.ts, src/lib/next-auth/auth.ts
- close #78 
- 메인페이지 오늘의 감정선택과 최신댓글 불러오기
=> fix(#78)메인페이지 오늘의 감정&댓글 부분 토큰연결

src/app/epigrams/page.tsx, src/app/oauth/kakao/page.tsx
- close #87 
kakao redirect uri 변경
=>  Fix(#87) : kakao redirect uri 변경

src/app/sample/_components/Su.tsx
=> fix: build error

src/app/page.tsx, src/app/sample/_components/Su.tsx, src/components/TodayEmotion.tsx
- close #112 
오늘의 감정 체크 안되던거 다시 체크되게 api연동
api를 연동시켜놔서 블록이 잘 되는데 지금 로컬스토리지에 값이 있으면 다시 재클릭이 안되게 해놨습니다 참고해주세요~!
=> fix:오늘의 감정 api 연결 수정 작업

src/app/addepigram/[id]/page.tsx, src/app/mypage/_components/MyCalender/MyCalender.tsx, src/app/mypage/page.tsx, src/components/EpigramForm.tsx, src/lib/Epigram.ts
- close #111 
- 랜딩 페이지/ 시작하기 버튼 경로 수정
- 에피그램 포스팅,수정 페이지/ 세션의 유저토큰 연결
- 마이페이지 / 캘린더와 감정 순서 변경
- 마이페이지 / 캘린더에 세션유저 id 연결
=> Fix(#111): 세션의 유저 토큰 연결

src/app/mypage/_components/MyCalender/MyCalender.tsx, src/app/mypage/page.tsx, src/app/sample/_components/Gyeong.tsx
- close #118 
api함수 실행전에 토큰값을 못받아오는 것 같아서 page에서 받아오는 걸로 수정했습니다!
=> Fix(#118): 캘린더 렌더링 버그 수정

src/components/TodayEmotion.tsx
- close #129 
- 메인페이지에서 오늘의 감정을 누를시 로컬스토지에 감정이 저장되고 디스에이블 되면서 그 부분을 흐리게 표시해두고 선택이 안되게 해놨습니다.
- 마이페이지에서는 로컬스토리지에 감정이 있지만 감정을 재선택 가능하게 만들었습니다.
https://github.com/user-attachments/assets/adb44740-88ce-4120-aad5-9cb8ac777b63
1. 메인 페이지에서 감정이 로컬스토리지에 있을 시 흐려지게 만들었는데 별로면 말씀해주세요~!
2. 마이페이지에서는 로컬스토리지에 감정이 있지만 api로는 잘 보내지는거 확인했습니다~!
=> Fix(#129):오늘의 감정 메인페이지와 마이페이지 차별점 수정

src/app/mypage/_components/TodayEmotionHeader.tsx, src/components/TodayEmotion.tsx, src/middleware.ts
- close #141 
- 오늘의 감정에서 이모티콘 누를 때 마다 로컬스토리지도 변화되고 api도 잘 불러오고 잘 보내지는걸로 확인!
https://github.com/user-attachments/assets/d7aba488-6f54-48f2-a8db-e210463a1aa7
=> fix:오늘의 감정 마이페이지 로컬스토리지관리

src/app/mypage/_components/TodayEmotionHeader.tsx, src/app/page.tsx
- close #140
전체적으로 피그마에 맞게 수정했습니다
framer-motion을 추가했습니다
렌딩페이지에서 모바일, 테블릿, pc 화면에서 section2의 사진들이 반응형으로 달라지는데 나중에 시간나실때 구현하시면 좋을 듯 합니다 !
=> Design(#140): 렌딩페이지 css 수정 및 framer-motion 등록

src/app/feed/[id]/_component/EpigramCommentSection.tsx
- close #147 
에피그램 댓글 무한스크롤 구현(Intersection Observer)
https://github.com/user-attachments/assets/55dfd306-89de-4e25-af36-b46294ef764e
댓글리스트가 큰 데이터를 불러오질 않아서 무한스크롤로 불러올때의 0.1~0.2초?만에 순식간에 다음 댓글을 불러오다보니 로딩을 특별히 css를 꾸미진 않았고 간단하게 텍스트로만 로딩중인걸 구현했습니다.
=> Feat(#147):에피그램 댓글 무한스크롤 구현

src/components/header/MainHeader.tsx
- close #170 
- 메인 헤더 부분의 프로필 부분에 공용컴포넌트 케밥 적용
공용컴포넌트로 해서 잘 적용 됩니다!
=> Fix(#170):메인 헤더 케밥 공용컴포넌트 작업

src/components/Comment/CommentItem.tsx
- close #193 
댓글 삭제이후 뜨는 삭제안내 모달 확인시  toast 뜨도록 구현
=> (feat#193): 댓글 삭제 toast 적용

src/app/page.tsx
- close #195 
- 세션2와 세션3 사이간격 조정
- 버튼 cursor 처리
=> Fix(#195): 세션 간격 조정 및 버튼 커서 처리

next.config.ts, src/app/mypage/_components/MyUserProfile.tsx, src/app/oauth/kakao/page.tsx, src/lib/next-auth/auth.ts, src/middleware.ts, src/types/Oauth.ts
- close #178
카카오 로그인 정보를 session에 저장하는 로직으로 수정
아직 테스트가 많이 되지 않아서 다들 테스트 해보시고 수정사항 있으면 말씀 주세요
메인 리뷰어는 은경님인데 일단 다들 테스트 해보시라고 모두 리뷰어로 달아놓겠습니다
=> Fix(#178) : 카카오 로그인 auth js로 수정

src/app/feed/page.tsx, src/app/mypage/_components/MyCommentList.tsx, src/app/mypage/page.tsx, src/components/FeedList/index.tsx, src/components/skeletons/SkeletonCommentCard.tsx, src/components/skeletons/SkeletonMyCalender.tsx, src/components/skeletons/SkeletonMyCart.tsx
- close #206 
- 마이페이지 캘린더, 차트, 캘린더 스켈레톤 UI 제작
- 피드 리스트 스켈레톤 UI으로 교체
=> feat(#206): 마이페이지 스켈레톤 UI 작업

src/app/mypage/_components/MyUserProfile.tsx, src/app/oauth/kakao/page.tsx
- close #204
마이페이지 프로필에 스켈레톤을 구현했습니다
로딩 부분을 if로 하는 대신 아래 return에 옮겨서 작성
카카오 리디렉션 페이지의 return에 로그인 대기시간동안 spinner를 리턴하도록 설정
https://github.com/user-attachments/assets/fc1d747f-7021-4ca6-8bec-8030b03f82df
https://github.com/user-attachments/assets/93a781d8-f502-4d4d-8b5e-a81a213cb36e
=> Design(#204) : 마이페이지 프로필에 스켈레톤 구현 카카오 로그인시 redirect page에 spinner 구현

src/components/EpigramForm.tsx
- close #216 
에피그램이 작성되지 않던 버그를 수정했습니다! 조건문 오류였네요 ㅎㅎ....
=> Fix(#216): 에피그램 작성 버그 수정

src/app/auth/signup/page.tsx, src/app/search/page.tsx, src/components/Tag/Tags.tsx
- close #220 
태그 폰트 수정했습니다!
회원가입에 있던 error state를 아예 지워버리고 알림 띄워주는 것으로 바꿔뒀습니다~
검색 페이지의 폰트들이 다 이롭게 폰트로 되어있는 것 같아서 pretendard인곳들은 폰트를 바꿔줬습니다!
=> Fix(#220): 태그와 회원가입 UI 수정

src/app/mypage/_components/MyCommentList.tsx, src/app/mypage/_components/MyTabMenu.tsx, src/components/FeedList/index.tsx, src/hooks/usePaginatedList.ts, src/stores/paginatedListStore.ts
- close #222 
- 마이페이지 탭메뉴 로딩 오류 수정
=> Fix(#222): 마이페이지 탭메뉴 로딩 오류 수정

src/app/auth/login/page.tsx, src/components/header/MainHeader.tsx
=> Fix(#225): 메인헤더 / 로그인폼 리팩토링
