10gosu1/FE12_Team5_epigram

src/app/sample/_components/Jin.tsx
src/components/Tags.tsx

- close #40 
태그 공용컴포넌트 구현
해당 컴포넌트에서 타입 지정
컴포넌트에 x버튼 생성. x버튼 클릭시 태그 삭제 구현
반응형 구현.
https://github.com/user-attachments/assets/958973a9-dd0d-441d-ab8b-f24659507dcf
삭제 로직은 가져가서 사용하는 부모컴포넌트에서  onRemoveTag 함수를 정의해야함.
(이런식으로..)
그리고... 피그마에서는 원래 x버튼이 없었지만, 만들어놓은 상태.. 입력창안에 태그가 나오는식이면 키보드 백스페이스 방식으로 지우는걸 구현할 수 있기는한데, 피그마상 입력상자 아래쪽에 태그가 나오다보니 삭제 기능 구현이 있는게 좋을듯하여 만들었습니다.

feat(#40): 태그 공용컴포넌트 구현

---

src/app/auth/login/page.tsx
src/app/auth/signup/page.tsx
src/lib/next-auth/auth.ts
src/types/auth.ts

- close #46 
-회원가입페이지도 nextauth와 연결시킴.
현재 확인해보니 로그인페이지와 회원가입 페이지의 유효성 검사를 스키마가 아닌 개별적으로 하는 것 같습니다.. 그래서 그거에 대한 수정이 필요하고 논의 사항으로는 현재 api에서 에러메세지를 전달해주는데 로그인할 때는 이메일이 다르면 '존재하지 않는 이메일입니다.' 그리고 비밀번호가 다를 시 '비밀번호가 일치하지 않습니다.' 라고 메세지를 전달해줍니다. 이것에 대한 내용을 일반 사용자들에게 보여지게 할지 아니면 지금 현재 독자적으로 '이메일또는 비밀번호가 다릅니다.'라고 메세지내용을 나타나게 했는데 이것으로 할지 의논이 필요합니다. 일단 sessionToken을 앞으로 작업해가야하는데 써야할거 같아서 먼저 올리고 멘토님이 말하신 내용과 수정할 부분들은 앞으로 조금씩 수정해나가겠습니다.

fix:회원가입페이지 nextauth와의 연결

---

src/app/sample/_components/Gyeong.tsx
src/components/Button/ClientButton.tsx
src/components/Button/ServerButton.tsx

- close #39 
프로젝트 내부에서 공용으로 사용할 수 있는 버튼 컴포넌트를 구현했습니다.
ServerButton.tsx 서버 컴포넌트
ClientButton.tsx 클라이언트 컴포넌트로 나뉘어져 있으니
필요한 기능에 따라 사용하시면 됩니다.
**- ServerButton** (Link/span)
페이지 내부에서 다른 주소로 이동만 시켜주는 버튼
**필수 prop**
isValid: 버튼의 disable 유무를 선택합니다.
href: Link를 클릭시 이동할 위치를 string으로 받습니다. ex) '/'
children: 버튼 내부에 들어갈 내용 ex)로그인, 회원가입, 시작하기....
**선택 prop**
className: 버튼 디자인을 커스텀할 수 있습니다. px와 py등등 각 페이지에서 다르게 쓰이는 디자인을 적용할때 활용해주세요!
isRounded: 이 속성을 주면 동그란 버튼이 됩니다. 기본적으로 false입니다.
**- ClientButton** (button)
onClick속성이 필요하시거나 form 제출
**필수 prop**
isValid: 버튼의 disable 유무를 선택합니다.
children: 버튼 내부에 들어갈 내용
**선택 prop**
type: button태그 type을 submit과 button중 선택할 수 있습니다. 기본 button
onClick: 버튼 클릭시 실행할 함수를 전달할 수 있습니다.
className: 버튼 디자인을 커스텀
isRounded: 동그란 버튼. 기본 false

Feat(#39): 공용컴포넌트 버튼

---

public/assets/icons/x_gray.svg
src/app/addepigram/layout.tsx
src/app/addepigram/page.tsx
src/app/epigrams/posting/page.tsx
src/app/globals.css
src/components/Tags.tsx
src/components/TagsInput.tsx
src/components/TagsInputWithList.tsx
src/lib/Epigram.ts

- close #58 
/addepigram 페이지의 에피그램을 작성할 수 있는 페이지 입니다.
현재 값 입력을 받고 api에 토큰을 넣으면 POST요청까지 가능한 상태입니다.
게시글 수정의 경우 initialValue값을 전달하려면 게시글과 수정글이 부모자식 관계여야하는데,
저희는 페이지 위치가 아예 다르기 때문에 이를 어떻게 전달할지 의논이 필요할 것 같습니다.
생각하고 있는 방식은 총 2가지 입니다.
1. 에피그램 상세페이지에서 수정하기 클릭시 useRouter로 페이지 이동 => /addepigram/[id].tsx 로 id값을 활용하여 api요청을 보내 getEpigram으로 초깃값 가져오기. 
2. Context를 활용하여 에피그램 값을 전역으로 관리하기 => 에피그램 상세페이지에서 수정하기 클릭시 useRouter로 페이지 이동 => Context로 필요한 값 가져오기.
UI디자인은 완성된 상태입니다.
content내용은 500자로 제한했으며,그 이상으로는 작성할 수 없도록 막아뒀습니다. 500자를 넘어가면 경고메세지를 띄우는것 보다는, 실시간으로 작성중인 글자수를 오른쪽위에 띄워주는 편이 직관적이라고 생각하여 추가했습니다.
global.css에 커스텀 스크롤바를 만들어뒀으니 필요하실때 쓰시면 됩니다.
현재 빌드오류는 제 페이지의 문제가 아닌 것 같아 이대로 올려둡니다!
https://github.com/user-attachments/assets/4d7c3876-d46e-402c-96b6-5a25255541db
- 게시글 수정시 initialValue값을 전달 방식

Feat(#58): 에피그램 만들기수정하기

---

package-lock.json
package.json
public/assets/icons/down_gray.svg
src/app/mypage/_components/MyCalender/CustomCalender.tsx
src/app/mypage/_components/MyCalender/EmotionFilter.tsx
src/app/mypage/_components/MyCalender/MyCalender.tsx
src/app/mypage/_components/MyCalender/custom-calendar.css
src/app/mypage/page.tsx
src/app/sample/_components/Gyeong.tsx
src/app/sample/page.tsx
src/types/Emotionlog.ts

- close #94 
마이페이지에 들어가는 캘린더 기능을 구현했습니다!
기능구현을 우선으로 하다보니 코드가 길어지고 정리해야할 부분이 있는데, 코드 리팩토링 기간에 수정해보겠습니다...!
감정 로그를 가져오는 유저 아이디는 임의로 넣어둔 상태이고, 필터링도 가능합니다.
날짜 format을 위한 moment 라이브러리와
react-calendar 캘린더 라이브러리를 활용했습니다.
react-calendar 캘린더를 커스텀하는 과정에서 지정된 class에 스타일을 넣어줘야해서 어쩔수없이 css파일을 따로 하나 만들어뒀습니다.
감정log를 가져오는 과정에서 선택한 달의 데이터만 가져올 수 있는 듯 한데...
그렇게 되면 파란색으로 표시한 부분의 데이터는 비게 됩니다.
이 경우 어떤식으로 해야할지 고민입니다.
api요청을 이전달 + 이번달 + 다음달 이러한 방식으로 3번 해야할지....
아니면 이번달만 보여주도록 해야할지....
이건 한번 다 같이 이야기 해봤으면 좋겠습니다!

Feat(#94): 마이페이지 캘린더

---

src/app/auth/login/page.tsx
src/app/auth/signup/page.tsx
src/app/oauth/google-callback/page.tsx
src/app/sample/_components/Su.tsx
src/components/header/MainHeader.tsx
src/lib/next-auth/auth.ts
src/lib/next-auth/auth_provider.tsx

- close #121 
- 로그인과 회원가입 실패시 오류 메시지 수정
- 로그아웃시 로그인 페이지로 이동
- 토큰 유효기간 만료시 자동발급 설정
현재 세션에 토큰 정보 보이는것을 수정하는것 빼곤 다했습니다. 그부분이 오래 걸릴거 같아서 우선 다른 바로바로 수정 가능한 부분 부터 하겠습니다.
토큰을 혹시 다시 못 받아올 시 말씀해주시면 감사하겠습니다.(작업하다 만료되서 다시 해보니 작동안되는걸 확인했습니다 수정해놓겠습니다.)

Fix(#121_ 로그인과 회원가입 부분 수정

---

src/app/feed/[id]/_component/EpigramCommentList.tsx
src/app/feed/[id]/_component/EpigramCommentSection.tsx
src/app/main/page.tsx
src/app/mypage/_components/MyCommentList.tsx
src/app/mypage/_components/MyComments.tsx
src/components/Comment/CommentEmpty.tsx
src/components/Comment/CommentList.tsx
src/components/UK/InfiniteList.tsx
src/lib/Comment.ts
src/lib/Epigram.ts
src/stores/pageStores.ts

- close #133 
1. 댓글 더보기 스냅샷 적용
2. 로그인 유저 댓글  수정/삭제 버튼 활성
(기존 토큰 하드코딩식에서 세션기반인증처리후 본인 댓글은 본인에게만 수정/삭제 버튼 활성화 되도록 구현)
1) 댓글 더보기 스냅샷 적용
https://github.com/user-attachments/assets/a87ce0b3-d467-4e1c-9321-efd1bba7873c
2) 로그인 유저 댓글  수정/삭제 버튼 활성
https://github.com/user-attachments/assets/459f5c92-e937-47c6-b33b-f2333abdbfc9
리뷰러가 주섭님이라 딱 의논할 내용 전달 드리기 적절한거 같은데,
현재 저가 담당하는 모든 댓글부분이 로그인후(토큰발급후) 일정시간이 지나면 토큰 만료가 되어서
그런지 그이후는 댓글 리스트 조회나 본인의 댓글수정/삭제를 이용할 수 가 없던데,, 이거 auth를 수정을 해야하나요? 아니면 저의 코드 로직을 바꿔야 하는건지...

Fix(#133): 댓글 더보기 스냅샷 적용

---

src/app/main/_conponents/todayEpigrams.tsx
src/app/main/page.tsx

- close #143 
오늘의 에피그램 없을 때 나타나는 이미지와 검수사항에 있던 반응형에 대해 수정사항을 수정한 수정본입니다.
https://github.com/user-attachments/assets/182495ec-0152-4c24-a5ca-996b127ff404
-현재 오늘의 에피그램이 없을 때 나타나는 이미지를 한솔님께서 만들어 놓으신 에피그램이 없을 때 나타나는 이미지를 저도 사용했는데 통일성있게 하는게 좋을거 같아서 가져다가 썼는데 혹시 다른것으로 만들었으면 좋겠다는 분이나 가져다 쓰지 않았으면 좋겠다 하시는분 계시면 수정하도록 하겠습니다.

Fix: 오늘의 에피그램 없을 때 나타나는 이미지 및 css 수정 작업

---

src/app/mypage/_components/TodayEmotionHeader.tsx
src/app/mypage/page.tsx

- close #148
자바스크립트 함수로 오늘의 감정의 날짜에 오늘 날짜를 보여주도록 하였습니다.
layout도 div 태그를 오늘의 감정 컴포넌트를 감싸여 아래 컴포넌트들과 비슷해지도록 수정하였습니다
은경님이 말씀해주신 라이브러리 쓰려다가 라이브러리가 너무 많으면 로딩 속도가 느려질 것 같아서 일단 javascript 내장 함수로 구현하였습니다.

Fix(#148) : 마이페이지 오늘의 감정 날짜 로직 변경 (오늘 날짜를 보여주도록)

---

src/app/auth/_component/SocialLogins.tsx
src/app/auth/layout.tsx
src/app/auth/login/page.tsx
src/components/FeedList/index.tsx
src/components/header/MainHeader.tsx
src/stores/pageStores.ts

- close #139 
- 메인 헤더 : 로고 클릭시 메인 페이지로 이동
- 메인 헤더 : 아바타 hover 시 cursor 적용
- 메인 헤더 : 아바타 토글 메뉴 hover 시 border-radius 적용
- 피드 페이지 : 피드 불러오는 store 분리하기
- 로그인 페이지 : 전반적인 css 피그마랑 맞추기 (반응형 포함)
- 로그인 페이지 : 패스워드 보기 버튼에 cursor 적용

fix(#139): 2차 검수사항 수정 (메인 헤더/피드 페이지/로그인 페이지)

---

src/middleware.ts

이동, 로그인후 랜딩 페이지 접속 불가
- close #131
로그인 안된 상태에서 /feed나 /feed의 하위 페이지에 접속 불가
로그인 후 자동으로 main 페이지로 이동
로그인후 렌딩 페이지에 접속 불가
middleware 고치니 회원가입 후 바로 /main으로 이동하게 되었습니다
https://github.com/user-attachments/assets/bd61edf6-3b77-470e-ac47-6d4aa784733b

Fix(#131) : 로그인후 feed에 접속 불가 로직, 로그인 후 자동으로 main 페이지로

---

src/lib/next-auth/auth.ts

- close #153 
- accessToken 만료시 refreshToken을 활용해 재발급 해오는 작업
https://github.com/user-attachments/assets/c5f5c596-8a37-4073-a950-9e7a69b650db
- 제가 우선 accessToken만료 기간을 30분정도로 잡고 체크 했을 땐 accessToken 만료되면 refreshToken을 잘 받아오는걸 확인했습니다. - 백엔드에서 따로 Token 값들의 유효기간이 설정되어 있으니 제가 설정한 유효기간은 지웠고 난중에 확인해봤을 때 제대로 못받아오면 말씀 해주시면 다시 수정해 놓겠습니다.

Fix(#153): 토큰 만료시 자동 재발급

---

src/app/mypage/_components/MyChart/EmotionPieChart.tsx
src/components/TodayEmotion.tsx

- close #161 
-마이 페이지 차트부분 반응형으로 만들고 오늘의 감정 부분 메인페이지에서 클릭하여 블록색을 나타내는것을 마이페이지로 넘어왔을 때 똑같이 표시하기로 설정
https://github.com/user-attachments/assets/c7002990-3148-4c41-a17c-25907953fe84
- pc버전일 때 오늘의 감정 차트 부분이 너무 어색하고 크기가 작아서 키우고 오늘의 감정 부분에서 메인페이지에서 클릭하면 그 블록처리한 것이 마이페이지로는 넘어오지 않아서 그부분 수정하였습니다.

fix:오늘의 감정 block 지정과 감정차트부분 css 수정

---

src/app/feed/[id]/_component/CommentInput.tsx
src/components/Comment/CommentItem.tsx
src/components/Modal/ModalUserProfile.tsx

- close #167 
1. 댓글프로필 모달창 프로필 이미지 연동
2. 에피그램 댓글 작성 프로필 이미지 연동
1. 댓글프로필 모달창 : 프로필 이미지 기본 이미지만 나오던 문제 수정
2. 에피그램 댓글 작성 프로필 이미지 : 기존 기본 이미지가 엑박이 뜨던 문제 수정

Feat/167/댓글프로필 모달창 프로필 이미지 연동 / 에피그램 댓글 작성 프로필 이미지 연동

---

src/app/feed/[id]/_component/CommentInput.tsx
src/components/Comment/CommentItem.tsx

- close #169 
스타일 수정사항
1. 댓글 수정모드 : 공개/비공개 토글 스타일 수정
2. 댓글 작성/수정 : 플레이스홀더 색상 변경
3. 댓글 작성/수정 입력란 : 포커스아웃라인 색상 변경 (회원가입/로그인폼과 동일)
https://github.com/user-attachments/assets/d9aea7eb-0cae-4c43-ac32-ffd14b6e4212

fix(#169): 댓글 css 스타일 수정

---

src/components/Tag/TagsInput.tsx
src/components/TagsInput.tsx

- close #165 
- 피드 만들기 태그 입력 부분에서 input 한글 두번 입력되는 오류 해결!
맥북의 크롬에서만 생기는 오류지만 해결했습니다!

Fix(#165): 태그 input 한글 두번 입력 오류 수정

---

src/app/auth/login/page.tsx
src/app/auth/signup/page.tsx
src/components/Kebab.tsx

- close #180 
- 로그인과 회원가입에서 성공 및 실패 했을 때 거기에 맞는 toast사용
- 메인 헤더에서 프로필 누를시 피드뒤에 케밥이 적용되서 z-index를 줘서 앞에 나오게함.
아주 잘나옵니다.
onSubmit을 설정해놨을 때 onClick이벤트를 설정하지 않아도 type="submit"을 하면 가장 가까운 form 태그의 onsubmit을 실행!
예시로는 로그인과 회원가입 페이지 코드를 보시면 됩니다!
```js
const onSubmit = async (data: LoginFormInputs) => {
setError(''); // 기존 에러 초기화
setErrorEmail('');
setErrorPassword('');
const res = await signIn('credentials', {
email: data.email,
password: data.password,
redirect: false, // 자동 리다이렉트 방지
}); // 응답 로그 확인
if (res?.error) {
setError('이메일 또는 비밀번호가 다릅니다.'); // NextAuth에서 받은 에러 메시지를 그대로 사용
notify({ type: 'error', message: '로그인에 실패했습니다.' });
return;
}
notify({ type: 'success', message: '로그인에 성공하였습니다.' });
router.push('/');
};
return(
<form onSubmit={handleSubmit(onSubmit)} className="flex w-full flex-col …
```

Fix(#180):로그인과 회원가입 성공 및 실패 시 toast적용 그리고 메인헤더 z-index적용

---

src/app/mypage/_components/MyUserProfile.tsx
src/lib/patchUserInfo.ts

- close #184
프로필 변경, 취소, 중복 닉네임시 각자 다른 toast 기능을 추가하였습니다

 feat(#184) : 마이페이지 프로필 toast 기능 추가

---

src/app/addepigram/[id]/page.tsx
src/app/auth/signup/page.tsx
src/app/main/_conponents/LatestEpigrams.tsx
src/app/main/_conponents/todayEpigrams.tsx
src/app/main/page.tsx
src/app/mypage/_components/MyCalender/EmotionFilter.tsx
src/app/mypage/_components/MyCalender/MyCalender.tsx
src/app/mypage/_components/TodayEmotionHeader.tsx
src/app/mypage/page.tsx
src/components/EpigramForm.tsx
src/components/PageBackground.tsx
src/components/TodayEmotion.tsx
src/lib/Epigram.ts
src/types/Epigram.ts

- close #181 
**에피그램 작성/수정**
- 에피그램 제출 폼 함수 관심사정리
- 에피그램 폼 제출 시 로딩 적용
**마이페이지**
- 마이페이지 캘린더 로딩 적용
- 오늘의 감정 색상 변경 => 기존에는 메인페이지와 마이페이지에서의 감정을 클릭시 focus되는 테두리 색상이 다른줄 알았는데, 감정마다 테두리 색상이 다른것으로 확인하여 고쳤습니다.
**회원가입**
- 회원가입하고 폼 제출시 로딩 적용
메인 페이지와 마이페이지의 title 글자들에 semibold가 적용이 안되어있는것 같아서 따로 수정했습니다.
마이페이지의 각 컴포넌트들의 간격이 이상한 것 같아서 감싸고 있는 레이아웃용 div태그도 조금 수정했습니다.
오늘의 감정
https://github.com/user-attachments/assets/79d37d75-56ec-4cfe-a952-117f917f89d4
폼 제출시 아래처럼 로딩이 되도록 해뒀습니다.

Fix(#181): 에피그램과 회원가입 리팩토링

---

src/app/feed/[id]/_component/CommentInput.tsx
src/app/feed/[id]/_component/EpigramCommentSection.tsx
src/app/mypage/_components/MyCommentList.tsx
src/app/mypage/_components/MyUserProfile.tsx
src/components/Comment/CommentItem.tsx
src/components/Comment/CommentList.tsx
src/lib/User.ts

- close #199 
1. 마이페이지에서 프로필 수정후(이미지, 닉네임) 댓글 아이템이 나오는 부분 실시간으로 프로필 이미지 / 닉네임 업데이트
https://github.com/user-attachments/assets/2547fc20-c726-4c90-9548-3496e710e1b1

Fix/199/상세페이지 댓글작성 프로필 이미지 실시간 연동
